language: python

git:
    depth: false

python:
    - "3.6"
    - "3.7"
    - "3.8"

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - pytest
    - pipenv run dist
    - pipenv run dist-check
