language: python

git:
    depth: false

python:
    - "3.6"
    - "3.7"
    - "3.8"
    - "3.9"
    - "3.10"

install:
    - pip install pipenv
    - pipenv install --dev

script:
    - pipenv run test
    - pipenv run dist
    - pipenv run dist-check
