# SPDX-FileCopyrightText: 2024-now, Alex Turbov <zaufi@pm.me>
# SPDX-License-Identifier: CC0-1.0

name: Checking `pre-commit` hooks

on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master

jobs:
  pre-commit-checks:
    name: Checking `pre-commit` hooks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Python env
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: pip

      - name: Checking configured hooks
        uses: pre-commit/action@v3.0.1
